can:
  devices:
  - instance: CAN1
    name: '1'
  - instance: CAN2
    name: '2'
  enabled: true
gpio:
  configs:
  - custom_name: ACCL_CS
    has_exti: false
    ioc_label: ACCL_CS
    pin: PA4
    type: OUTPUT
  - custom_name: GYRO_CS
    has_exti: false
    ioc_label: GYRO_CS
    pin: PB0
    type: OUTPUT
  - custom_name: ACCL_INT
    has_exti: true
    ioc_label: ACCL_INT
    pin: PC4
    type: EXTI
  - custom_name: GYRO_INT
    has_exti: true
    ioc_label: GYRO_INT
    pin: PC5
    type: EXTI
  enabled: true
mm:
  enabled: true
pwm:
  configs:
  - channel: TIM_CHANNEL_1
    custom_name: IMU_HEAT_PWM
    label: IMU_HEAT_PWM
    timer: TIM10
  enabled: true
spi:
  devices:
  - instance: SPI1
    name: '1'
  enabled: true
time:
  enabled: true
uart:
  devices:
  - instance: USART3
    name: '3'
  enabled: true
